### ISSUE TITLE
Stack overflow on large states and measurements

### ISSUE THREAD

**Issue by cr-walker** [strawlab/adskalman-rs#19]
This may be impossible due to underlying `nalgebra` limits, but here is the use case:
- Keep compile-time type annotations (i.e. matrix size validation based on `SS`- and `OS`-style types or values).
- But avoid stack overflow when handling large matrices (e.g. `SS = Const<100>`).

So far it looks like nalgebra's `OMatrix` type will infer a stack location for the result of matrix operations on an `OMatrix` even if one defines a custom heap-based allocator (see https://discourse.nphysics.org/t/force-the-matrix-to-be-heap-allocated/361/3).

And this library requires state and measurement matrices to be `OMatrix`!

So is there any reasonable solution beside a rewrite of this library? (New to Rust, may be missing something obvious.)

**Comment by astraw** [comment]
Interesting request. I've only used smallish states and been happy to store it on the stack.

It would be possible to make the underlying storage generic (i.e. that `state` has type `Vector<R, SS, S1>` instead of `OVector<R, SS>`). However, I'm not sure how far this can go. I think all requirements on `DefaultAllocator` would have to be dropped (and replaced with a requirement on `Clone`?) but AFAICS one problem is that nalgebra only provides a Cholesky decomposition for DefaultAllocator types. I pushed a work in progress branch at `storage-generic-wip` in which I started playing with this. You could continue to try to get working, but I don't have more time available for this. Build with `cargo build --release --no-default-features` to minimize the amount of conversions necessary in the first instance.

Perhaps a larger scale refactoring could make this possible. Just brainstorming: perhaps `StateAndCovariance` could be made generic over the storage but the rest of the library changed to deal with that (using an API different to what exists now).

I think a small example that reproduces the stack overflow could potentially help think about minimal changes that would solve the issue.

**Comment by cr-walker** [comment]
Thanks for the detailed response.

I'm compiling the Rust to WASM for an in-browser simulation so have limited control over stack size: the overflow either happens during the update step (e.g. I think it's sometimes this line `let s = (h * p * ht) + r;`) or just setting up the simulation (`OMatrix::<f64, Const<300>, Const<300>::identity()`) is enough to do the trick.

Because we're estimating the location of ~100 nodes using distance measurements I can split the problem up into a per-node EKF but I was hoping to use a single massive EKF as a baseline for position estimation accuracy.

Modifying the `StateAndCovariance` struct was exactly what I had in mind, thanks for the warning on missing Cholesky decomposition. Will give this a shot if I get insufficient accuracy with independent filters per node.

**Comment by astraw** [comment]
You could also "just" make a parallel implementation for heap-allocated data but copying and pasting the stack-allocated version and changing as necessary. The challenge I mention above with e.g. the Cholesky decomposition is making it generic over allocators but to simply get something working that shouldn't be necessary.
